version: '3'

services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - ./backend:/var/www:cached

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./backend:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    frontend:
        image: node:alpine
        container_name: front-end
        working_dir: /app
        volumes:
            - ./frontend:/app
        command: sh -c "rm -rf node_modules && npm install && npm run dev"
        depends_on:
            - php
        ports:
            - "3000:5173"
        expose:
            - 3000
        restart: unless-stopped

    mysql:
        image: mysql:latest
        container_name: mysql-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: book
            MYSQL_USER: book.user
            MYSQL_PASSWORD: 12345@book
        volumes:
            - ./database/data:/var/lib/mysql
            - ./database/scripts:/docker-entrypoint-initdb.d
        expose:
            - 3306
        ports:
            - "3306:3306"


